DROP DATABASE IF EXISTS tracker_db;
CREATE DATABASE tracker_db;

USE tracker_db;
-- DEPARTMENT TABLE
CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL
);
-- EMPLOYEE ROLE TABLE
CREATE TABLE employee_role (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  dept_id INTEGER,
 FOREIGN KEY (dept_id) REFERENCES department(id) ON DELETE SET NULL  
);
-- EMPLOYEE TABLE 
CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  employee_role_id INTEGER,
  manager_id INTEGER,
 FOREIGN KEY (employee_role_id) REFERENCES employee_role(id) ON DELETE SET NULL
);